
// Objective-C API for talking to the following Go packages
//
//	github.com/CriticalMoments/CriticalMoments/go_core
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gocore_FRAMEWORK_H__
#define __Gocore_FRAMEWORK_H__

#include "Gocore.objc.h"
#include "Universe.objc.h"

#endif
