// Objective-C API for talking to github.com/CriticalMoments/CriticalMoments/go_core Go package.
//   gobind -lang=objc github.com/CriticalMoments/CriticalMoments/go_core
//
// File is generated by gobind. Do not edit.

#ifndef __Gocore_H__
#define __Gocore_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT long GocoreGoAdd(long a, long b);

FOUNDATION_EXPORT NSString* _Nonnull GocoreGoPing(void);

#endif
