// Objective-C API for talking to github.com/CriticalMoments/CriticalMoments/go/appcore Go package.
//   gobind -lang=objc github.com/CriticalMoments/CriticalMoments/go/appcore
//
// File is generated by gobind. Do not edit.

#ifndef __Appcore_H__
#define __Appcore_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT long AppcoreGoAdd(long a, long b);

FOUNDATION_EXPORT NSString* _Nonnull AppcoreGoPing(void);

#endif
