name: Check Format
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go/go.mod'
        cache-dependency-path: go/go.sum

    - name: Golang vet
      run: cd go && go vet ./... && cd ..

    - name: Go fmt
      run: cd go && if [ "$(gofmt -d -l $(find . -type f -name '*.go'| grep -v "/vendor/\|/.git/") | wc -l)" -gt 0 ]; then exit 1; fi && cd ..

    - name: Run clang-format style 
      uses: jidicula/clang-format-action@v4.10.1
      with:
        clang-format-version: '13'
        check-path: 'ios'
        fallback-style: 'WebKit'
        include-regex: '^.*\.((((c|C)(c|pp|xx|\+\+)?$)|((h|H)h?(pp|xx|\+\+)?$))|(ino|pde|proto|cu|m))$'
