name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style 
      uses: jidicula/clang-format-action@v4.10.1
      with:
        clang-format-version: '13'
        check-path: 'ios/voicebox'
        fallback-style: 'WebKit'
        include-regex: '^.*\.((((c|C)(c|pp|xx|\+\+)?$)|((h|H)h?(pp|xx|\+\+)?$))|(ino|pde|proto|cu|m))$'
