name: Check For P0 Issues
on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  p0-check:
    name: Check for P0 issues
    runs-on: ubuntu-latest
    steps:

    - name: Check for P0 issue comments
      run: |
        todos=true
        grep -r TODO_P0 --exclude-dir=.git --exclude-dir=.github . || todos=false
        if [ "$todos" == true ]
        then
          echo "TODO_P0 issues found"
          exit 1
        fi
