name: Build xcframework Release

on: [push]
#on:
#  release:
#    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build_xcframework:
    name: Build an xcframework for this release 
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - uses: xavierLowmiller/xcodegen-action@1.1.2

      - name: Select xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app && /usr/bin/xcodebuild -version

      - name: Build xcode project files
        run: xcodegen generate --spec ./ios/project.yml 

      - name: Build xcframework using carthage
        run: carthage build --no-skip-current --use-xcframeworks

      - name: zip xcframework
        run: cp -r Carthage/Build/CriticalMoments.xcframework . && zip -r xcframework.zip CriticalMoments.xcframework

      - name: Upload xcframework to release
        uses: softprops/action-gh-release@v1
        with:
          files: xcframework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

