name: Build and Test Go

on: 
  push: 
    paths:
      - 'go/**'

jobs:
  build_and_test:
    name: Build and Test Go
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go/go.mod'
          cache-dependency-path: go/go.sum

      - name: Setup gomobile
        run: cd go && go install golang.org/x/mobile/cmd/gomobile && gomobile init && cd ..

      - name: Golang tests
        run: cd go && go test -v ./... && cd ..

      - name: Golang race condition tests
        run: cd go && go test -race -vet=off -v ./... && cd ..

      - name: Select xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app && /usr/bin/xcodebuild -version

      - name: Build go appcore xcframework
        run: ./go/build_appcore.sh 
