name: Build and Test

on: [push]

jobs:
  build_and_test:
    name: Build & test SPM
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go/go.mod'
          cache-dependency-path: go/go.sum

      - name: Setup gomobile
        run: cd go && go install golang.org/x/mobile/cmd/gomobile && gomobile init && cd ..

      - name: Golang tests
        run: cd go && go test -v ./... && cd ..

      - name: Build go appcore xcframework
        run: ./go/build_appcore.sh 

      - name: Select xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app && /usr/bin/xcodebuild -version

      - name: Build and test iOS Package and SampleApp
        run: cd ios/sample_app && xcodebuild -scheme SampleApp -testPlan TestPlan -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro' -skip-testing:SampleAppTests/SnapshotTests test && cd ../..
